### ISSUE TITLE
Suggestion：其实可以试试看log4js这个log模块

### ISSUE THREAD

**Issue by gamesgao** [GameShare/BLive_REPEAT#2]
我用这个写log，感觉还挺好看的，而且也应该可以输出到pm2，不知道你把console.log改成process.stdout.write是不能输出到pm2么？

**Comment by Long-Dream** [comment]
并不是，只是之前的写法因为进行了两次输出，所以在pm2的监控里面显示的是两行
改了之后的只输出一次，所以在pm2的监控里面也只就显示一行
颜色什么的还是很正常的www

**Comment by gamesgao** [comment]
原来如此
